spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: app
  datasource:
    url: ${SUPABASE_DB_URL}
    username: ${SUPABASE_DB_USERNAME}
    password: ${SUPABASE_DB_PASSWORD}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 0
      max-lifetime: 300000
      idle-timeout: 60000
      data-source-properties:
        prepareThreshold: 0
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SUPABASE_JWK_SET_URI}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false